//! Generates `lib/typescript/src/constants.ts` from the canonical Rust protocol
//! constants (`pathland_core::constants`) so the TypeScript DOM renderer's
//! wire-constant mirror cannot drift: every `export const` below is bound to the
//! Rust constant it must match, so a rename breaks this crate's compilation and
//! a revalue changes the emitted file (caught by the CI regen-diff check).
//!
//! The enum *codes* (alignment, shape kind, role, state, …) are protocol-semantic
//! values defined in `spec/MODIFIERS.md`/`spec/OPCODE.md` that today live only in
//! the specs and the renderers; they are enumerated here so the TS side is
//! generated rather than hand-mirrored. They are the renderer-facing copy of the
//! same maps the HTML renderers implement.

use pathland_core::{
    category, component_type, environment, event, flag, listener, meta, property_id, role, style,
    tree, value_type,
};
use pathland_render_html::{role_spec, token_spec};
use std::fmt::Write;
use std::io;
use std::path::{Path, PathBuf};

/// The canonical source of the emitted file (resolved relative to this crate).
pub fn constants_ts_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../typescript/src/constants.ts")
}

/// The canonical source of the generated token conventions.
pub fn tokens_core_ts_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../typescript/src/generated/tokens-core.ts")
}

/// The canonical source of the generated role→element conventions.
pub fn role_spec_ts_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../typescript/src/generated/role-spec.ts")
}

fn fmt_u8(v: u8) -> String {
    format!("{v:#04x}")
}

fn fmt_u16(v: u16) -> String {
    format!("{v:#06x}")
}

fn fmt_u32(v: u32) -> String {
    format!("{v:#010x}")
}

fn write_consts(out: &mut String, prefix: &str, items: &[(&str, String)]) {
    for (name, value) in items {
        writeln!(out, "export const {prefix}{name} = {value};").unwrap();
    }
}

/// The enum-code tables mirrored from `spec/MODIFIERS.md` / `spec/OPCODE.md`.
/// (These codes are protocol-semantic and have no `pathland_core` consts yet.)
fn enum_codes() -> Vec<(&'static str, Vec<(&'static str, u32)>)> {
    vec![
        ("ALIGN_", vec![("LEADING", 0), ("CENTER", 1), ("TRAILING", 2), ("FILL", 3)]),
        (
            "SHAPE_",
            vec![
                ("CIRCLE", 0),
                ("RECTANGLE", 1),
                ("ROUNDED_RECTANGLE", 2),
                ("CAPSULE", 3),
                ("ELLIPSE", 4),
                ("PATH", 5),
            ],
        ),
        (
            "TEXT_ALIGN_",
            vec![("LEADING", 0), ("CENTER", 1), ("TRAILING", 2)],
        ),
        (
            "TRUNCATION_",
            vec![("HEAD", 0), ("MIDDLE", 1), ("TAIL", 2)],
        ),
        ("CONTENT_MODE_", vec![("FIT", 0), ("FILL", 1)]),
        ("FONT_STYLE_", vec![("NORMAL", 0), ("ITALIC", 1)]),
        (
            "FONT_DESIGN_",
            vec![("DEFAULT", 0), ("SERIF", 1), ("ROUNDED", 2), ("MONOSPACED", 3)],
        ),
        ("TEXT_CASE_", vec![("NONE", 0), ("UPPERCASE", 1), ("LOWERCASE", 2)]),
        (
            "CONTROL_SIZE_",
            vec![("SMALL", 0), ("REGULAR", 1), ("LARGE", 2)],
        ),
        (
            "DATE_PICKER_MODE_",
            vec![("DATE", 0), ("TIME", 1), ("DATE_AND_TIME", 2)],
        ),
        (
            "PICKER_STYLE_",
            vec![("MENU", 0), ("SEGMENTED", 1), ("WHEEL", 2), ("RADIO_GROUP", 3)],
        ),
        (
            "TOGGLE_STYLE_",
            vec![("SWITCH", 0), ("CHECKBOX", 1), ("BUTTON", 2)],
        ),
        (
            "STATE_",
            vec![
                ("NORMAL", 0),
                ("DISABLED", 1),
                ("FOCUSED", 2),
                ("PRESSED", 3),
                ("SELECTED", 4),
                ("EXPANDED", 5),
                ("BUSY", 6),
            ],
        ),
    ]
}

/// Emit the full `constants.ts`.
pub fn emit_constants_ts() -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo run -p pathland-ts-codegen` (lib/rust). Do not edit.\n\
         // Wire constants are bound to `pathland_core::constants`; enum codes mirror\n\
         // spec/MODIFIERS.md + spec/OPCODE.md. Regenerate with `npm run regen`.\n\n\
         // Batch header\n",
    );
    write_consts(&mut out, "", &[
        ("MAGIC", format!("{:#x}", 0x504c504cu32)),
        ("VERSION", "1".into()),
        ("HEADER_SIZE", "16".into()),
        ("OPCODE_SIZE", "16".into()),
        ("FLAG_HOST_TO_GUEST", "0x0001".into()),
    ]);
    out.push_str("\n// Categories\n");
    write_consts(&mut out, "CAT_", &[
        ("TREE", fmt_u8(category::TREE)),
        ("STYLE", fmt_u8(category::STYLE)),
        ("EVENT", fmt_u8(category::EVENT)),
        ("META", fmt_u8(category::META)),
    ]);
    out.push_str("\n// TREE commands\n");
    write_consts(&mut out, "CMD_", &[
        ("CREATE_NODE", fmt_u8(tree::CREATE_NODE)),
        ("DELETE_NODE", fmt_u8(tree::DELETE_NODE)),
        ("INSERT_CHILD", fmt_u8(tree::INSERT_CHILD)),
        ("REMOVE_CHILD", fmt_u8(tree::REMOVE_CHILD)),
        ("MOVE_CHILD", fmt_u8(tree::MOVE_CHILD)),
    ]);
    out.push_str("\n// STYLE commands\n");
    write_consts(&mut out, "CMD_", &[
        ("SET_PROPERTY", fmt_u8(style::SET_PROPERTY)),
        ("SET_DESIGN_TOKEN", fmt_u8(style::SET_DESIGN_TOKEN)),
        ("SET_TEXT", fmt_u8(style::SET_TEXT)),
        ("SET_DATE", fmt_u8(style::SET_DATE)),
    ]);
    out.push_str("\n// META commands\n");
    write_consts(&mut out, "CMD_", &[
        ("RESET", fmt_u8(meta::RESET)),
        ("ENVIRONMENT", fmt_u8(meta::ENVIRONMENT)),
        ("RESYNC", fmt_u8(meta::RESYNC)),
    ]);
    out.push_str("\n// META::ENVIRONMENT field ids (spec/OPCODE.md §Environment fields)\n");
    write_consts(&mut out, "ENV_", &[
        ("VIEWPORT_WIDTH", fmt_u16(environment::VIEWPORT_WIDTH)),
        ("VIEWPORT_HEIGHT", fmt_u16(environment::VIEWPORT_HEIGHT)),
        ("ROUTE", fmt_u16(environment::ROUTE)),
    ]);
    out.push_str("\n// EVENT commands (host -> guest)\n");
    write_consts(&mut out, "CMD_", &[
        ("POINTER_DOWN", fmt_u8(event::POINTER_DOWN)),
        ("POINTER_MOVE", fmt_u8(event::POINTER_MOVE)),
        ("POINTER_UP", fmt_u8(event::POINTER_UP)),
        ("KEY_DOWN", fmt_u8(event::KEY_DOWN)),
        ("KEY_UP", fmt_u8(event::KEY_UP)),
        ("VALUE_CHANGED", fmt_u8(event::VALUE_CHANGED)),
        ("TEXT_CHANGED", fmt_u8(event::TEXT_CHANGED)),
        ("FOCUS_CHANGED", fmt_u8(event::FOCUS_CHANGED)),
        ("EDITING_CHANGED", fmt_u8(event::EDITING_CHANGED)),
        ("SUBMIT", fmt_u8(event::SUBMIT)),
        ("SCROLL", fmt_u8(event::SCROLL)),
        ("WHEEL", fmt_u8(event::WHEEL)),
        ("DATE_CHANGED", fmt_u8(event::DATE_CHANGED)),
        ("NAVIGATE", fmt_u8(event::NAVIGATE)),
    ]);
    out.push_str("\n// EVENT flags\n");
    write_consts(&mut out, "FLAG_", &[
        ("POINTER_SECONDARY", fmt_u16(flag::POINTER_SECONDARY)),
        ("HOVER_ENTER", fmt_u16(flag::HOVER_ENTER)),
        ("HOVER_LEAVE", fmt_u16(flag::HOVER_LEAVE)),
        ("KEY_REPEAT", fmt_u16(flag::KEY_REPEAT)),
        ("NAVIGATE_URL", fmt_u16(flag::NAVIGATE_URL)),
    ]);
    out.push_str("\n// EVENT_LISTENERS bits (spec/EVENTS.md)\n");
    write_consts(&mut out, "LISTEN_", &[
        ("POINTER_DOWN", fmt_u32(listener::POINTER_DOWN)),
        ("POINTER_MOVE", fmt_u32(listener::POINTER_MOVE)),
        ("POINTER_UP", fmt_u32(listener::POINTER_UP)),
        ("KEY_DOWN", fmt_u32(listener::KEY_DOWN)),
        ("KEY_UP", fmt_u32(listener::KEY_UP)),
        ("FOCUS", fmt_u32(listener::FOCUS)),
        ("EDITING", fmt_u32(listener::EDITING)),
        ("SUBMIT", fmt_u32(listener::SUBMIT)),
        ("SCROLL", fmt_u32(listener::SCROLL)),
        ("WHEEL", fmt_u32(listener::WHEEL)),
    ]);
    out.push_str("\n// Value types (spec/OPCODE.md)\n");
    write_consts(&mut out, "VAL_", &[
        ("U8", fmt_u8(value_type::U8)),
        ("U32", fmt_u8(value_type::U32)),
        ("I32", fmt_u8(value_type::I32)),
        ("F32", fmt_u8(value_type::F32)),
        ("STRING", fmt_u8(value_type::STRING)),
        ("ENUM", fmt_u8(value_type::ENUM)),
        ("COLOR", fmt_u8(value_type::COLOR)),
        ("DESIGN_TOKEN", fmt_u8(value_type::DESIGN_TOKEN)),
    ]);
    out.push_str("\n// Property IDs (spec/MODIFIERS.md)\n");
    write_consts(&mut out, 
        "PROP_",
        &[
            ("SPACING", fmt_u16(property_id::SPACING)),
            ("ALIGNMENT", fmt_u16(property_id::ALIGNMENT)),
            ("CONTENT_MARGINS", fmt_u16(property_id::CONTENT_MARGINS)),
            ("SHAPE_KIND", fmt_u16(property_id::SHAPE_KIND)),
            ("TEXT", fmt_u16(property_id::TEXT)),
            ("LINE_LIMIT", fmt_u16(property_id::LINE_LIMIT)),
            ("TEXT_ALIGNMENT", fmt_u16(property_id::TEXT_ALIGNMENT)),
            ("TRUNCATION_MODE", fmt_u16(property_id::TRUNCATION_MODE)),
            ("OFFSET_X", fmt_u16(property_id::OFFSET_X)),
            ("OFFSET_Y", fmt_u16(property_id::OFFSET_Y)),
            ("POSITION_X", fmt_u16(property_id::POSITION_X)),
            ("POSITION_Y", fmt_u16(property_id::POSITION_Y)),
            ("MIN_WIDTH", fmt_u16(property_id::MIN_WIDTH)),
            ("IDEAL_WIDTH", fmt_u16(property_id::IDEAL_WIDTH)),
            ("MAX_WIDTH", fmt_u16(property_id::MAX_WIDTH)),
            ("MIN_HEIGHT", fmt_u16(property_id::MIN_HEIGHT)),
            ("IDEAL_HEIGHT", fmt_u16(property_id::IDEAL_HEIGHT)),
            ("MAX_HEIGHT", fmt_u16(property_id::MAX_HEIGHT)),
            ("FIXED_SIZE_HORIZONTAL", fmt_u16(property_id::FIXED_SIZE_HORIZONTAL)),
            ("FIXED_SIZE_VERTICAL", fmt_u16(property_id::FIXED_SIZE_VERTICAL)),
            ("LAYOUT_PRIORITY", fmt_u16(property_id::LAYOUT_PRIORITY)),
            ("ASPECT_RATIO", fmt_u16(property_id::ASPECT_RATIO)),
            ("CONTENT_MODE", fmt_u16(property_id::CONTENT_MODE)),
            ("MINIMUM_SCALE_FACTOR", fmt_u16(property_id::MINIMUM_SCALE_FACTOR)),
            ("BACKGROUND_COLOR", fmt_u16(property_id::BACKGROUND_COLOR)),
            ("IMAGE_SOURCE", fmt_u16(property_id::IMAGE_SOURCE)),
            ("BORDER_WIDTH", fmt_u16(property_id::BORDER_WIDTH)),
            ("BORDER_COLOR", fmt_u16(property_id::BORDER_COLOR)),
            ("BORDER_RADIUS", fmt_u16(property_id::BORDER_RADIUS)),
            ("FONT_SIZE", fmt_u16(property_id::FONT_SIZE)),
            ("FONT_WEIGHT", fmt_u16(property_id::FONT_WEIGHT)),
            ("FONT_FAMILY", fmt_u16(property_id::FONT_FAMILY)),
            ("COLOR", fmt_u16(property_id::COLOR)),
            ("WIDTH", fmt_u16(property_id::WIDTH)),
            ("HEIGHT", fmt_u16(property_id::HEIGHT)),
            ("OPACITY", fmt_u16(property_id::OPACITY)),
            ("VISIBLE", fmt_u16(property_id::VISIBLE)),
            ("Z_INDEX", fmt_u16(property_id::Z_INDEX)),
            ("CLIPS_TO_BOUNDS", fmt_u16(property_id::CLIPS_TO_BOUNDS)),
            ("PADDING", fmt_u16(property_id::PADDING)),
            ("PADDING_TOP", fmt_u16(property_id::PADDING_TOP)),
            ("PADDING_RIGHT", fmt_u16(property_id::PADDING_RIGHT)),
            ("PADDING_BOTTOM", fmt_u16(property_id::PADDING_BOTTOM)),
            ("PADDING_LEFT", fmt_u16(property_id::PADDING_LEFT)),
            ("BORDER_EDGES", fmt_u16(property_id::BORDER_EDGES)),
            ("FONT_STYLE", fmt_u16(property_id::FONT_STYLE)),
            ("FONT_DESIGN", fmt_u16(property_id::FONT_DESIGN)),
            ("FONT_WIDTH", fmt_u16(property_id::FONT_WIDTH)),
            ("KERNING", fmt_u16(property_id::KERNING)),
            ("TRACKING", fmt_u16(property_id::TRACKING)),
            ("BASELINE_OFFSET", fmt_u16(property_id::BASELINE_OFFSET)),
            ("LINE_SPACING", fmt_u16(property_id::LINE_SPACING)),
            ("TEXT_CASE", fmt_u16(property_id::TEXT_CASE)),
            ("UNDERLINE", fmt_u16(property_id::UNDERLINE)),
            ("STRIKETHROUGH", fmt_u16(property_id::STRIKETHROUGH)),
            ("SHADOW_COLOR", fmt_u16(property_id::SHADOW_COLOR)),
            ("SHADOW_RADIUS", fmt_u16(property_id::SHADOW_RADIUS)),
            ("SHADOW_X", fmt_u16(property_id::SHADOW_X)),
            ("SHADOW_Y", fmt_u16(property_id::SHADOW_Y)),
            ("BLUR_RADIUS", fmt_u16(property_id::BLUR_RADIUS)),
            ("SATURATION", fmt_u16(property_id::SATURATION)),
            ("CONTRAST", fmt_u16(property_id::CONTRAST)),
            ("BRIGHTNESS", fmt_u16(property_id::BRIGHTNESS)),
            ("GRAYSCALE", fmt_u16(property_id::GRAYSCALE)),
            ("HUE_ROTATION", fmt_u16(property_id::HUE_ROTATION)),
            ("COLOR_MULTIPLY", fmt_u16(property_id::COLOR_MULTIPLY)),
            ("COLOR_INVERT", fmt_u16(property_id::COLOR_INVERT)),
            ("ROTATION_DEGREES", fmt_u16(property_id::ROTATION_DEGREES)),
            ("SCALE", fmt_u16(property_id::SCALE)),
            ("ALLOWS_HIT_TESTING", fmt_u16(property_id::ALLOWS_HIT_TESTING)),
            ("TINT", fmt_u16(property_id::TINT)),
            ("TRANSITION", fmt_u16(property_id::TRANSITION)),
            ("ROLE", fmt_u16(property_id::ROLE)),
            ("STATE", fmt_u16(property_id::STATE)),
            ("ENABLED", fmt_u16(property_id::ENABLED)),
            ("SELECTED", fmt_u16(property_id::SELECTED)),
            ("EVENT_LISTENERS", fmt_u16(property_id::EVENT_LISTENERS)),
            ("VALUE", fmt_u16(property_id::VALUE)),
            ("MIN_VALUE", fmt_u16(property_id::MIN_VALUE)),
            ("MAX_VALUE", fmt_u16(property_id::MAX_VALUE)),
            ("STEP_VALUE", fmt_u16(property_id::STEP_VALUE)),
            ("LABEL", fmt_u16(property_id::LABEL)),
            ("PROMPT", fmt_u16(property_id::PROMPT)),
            ("CONTROL_SIZE", fmt_u16(property_id::CONTROL_SIZE)),
            ("IS_SECURE", fmt_u16(property_id::IS_SECURE)),
            ("PROGRESS", fmt_u16(property_id::PROGRESS)),
            ("IS_INDETERMINATE", fmt_u16(property_id::IS_INDETERMINATE)),
            ("SELECTION", fmt_u16(property_id::SELECTION)),
            ("COLOR_VALUE", fmt_u16(property_id::COLOR_VALUE)),
            ("DATE_PICKER_MODE", fmt_u16(property_id::DATE_PICKER_MODE)),
            ("PICKER_STYLE", fmt_u16(property_id::PICKER_STYLE)),
            ("ACTION_ID", fmt_u16(property_id::ACTION_ID)),
            ("BINDING_ID", fmt_u16(property_id::BINDING_ID)),
            ("TOGGLE_STYLE", fmt_u16(property_id::TOGGLE_STYLE)),
            ("ROUTE", fmt_u16(property_id::ROUTE)),
            ("NAV_DEPTH", fmt_u16(property_id::NAV_DEPTH)),
            ("NAV_CHROME", fmt_u16(property_id::NAV_CHROME)),
        ],
    );
    out.push_str("\n// Width/height hints (WIDTH/HEIGHT values)\n");
    write_consts(&mut out, "WIDTH_", &[
        ("FILL", "-1".into()),
        ("HUG", "-2".into()),
    ]);

    for (prefix, items) in enum_codes() {
        let comment = match prefix {
            "ALIGN_" => "Alignment enum (protocol ENUM values)",
            "SHAPE_" => "SHAPE_KIND",
            "TEXT_ALIGN_" | "TRUNCATION_" | "CONTENT_MODE_" | "FONT_STYLE_" | "FONT_DESIGN_"
            | "TEXT_CASE_" => "TEXT_ALIGNMENT / TRUNCATION_MODE / CONTENT_MODE / FONT_STYLE / FONT_DESIGN / TEXT_CASE",
            "CONTROL_SIZE_" | "DATE_PICKER_MODE_" | "PICKER_STYLE_" | "TOGGLE_STYLE_" => {
                "CONTROL_SIZE / DATE_PICKER_MODE / PICKER_STYLE / TOGGLE_STYLE"
            }
            "STATE_" => "STATE (control/interaction state, spec/OPCODE.md semantic properties)",
            _ => "",
        };
        if !comment.is_empty() {
            writeln!(out, "\n// {comment}").unwrap();
        }
        let mapped: Vec<(&str, String)> = items
            .iter()
            .map(|(n, v)| (*n, format!("{v}")))
            .collect();
        write_consts(&mut out, prefix, &mapped);
    }

    // ROLE is bound to pathland_core::role (the canonical protocol catalog).
    out.push_str("\n// ROLE (semantic role, spec/OPCODE.md — bound to `pathland_core::role`)\n");
    write_consts(
        &mut out,
        "ROLE_",
        &[
            ("NONE", role::NONE.to_string()),
            ("BUTTON", role::BUTTON.to_string()),
            ("LINK", role::LINK.to_string()),
            ("HEADER", role::HEADER.to_string()),
            ("TEXT", role::TEXT.to_string()),
            ("IMAGE", role::IMAGE.to_string()),
            ("TEXT_FIELD", role::TEXT_FIELD.to_string()),
            ("SLIDER", role::SLIDER.to_string()),
            ("TOGGLE", role::TOGGLE.to_string()),
            ("CHECKBOX", role::CHECKBOX.to_string()),
            ("RADIO_BUTTON", role::RADIO_BUTTON.to_string()),
            ("STEPPER", role::STEPPER.to_string()),
            ("TAB", role::TAB.to_string()),
            ("TAB_BAR", role::TAB_BAR.to_string()),
            ("LIST", role::LIST.to_string()),
            ("GRID", role::GRID.to_string()),
            ("SCROLL_VIEW", role::SCROLL_VIEW.to_string()),
            ("ADJUSTABLE", role::ADJUSTABLE.to_string()),
            ("SUMMARY", role::SUMMARY.to_string()),
            ("MENU", role::MENU.to_string()),
            ("BANNER", role::BANNER.to_string()),
            ("NAVIGATION", role::NAVIGATION.to_string()),
            ("MAIN", role::MAIN.to_string()),
            ("CONTENT_INFO", role::CONTENT_INFO.to_string()),
            ("COMPLEMENTARY", role::COMPLEMENTARY.to_string()),
            ("ARTICLE", role::ARTICLE.to_string()),
            ("SECTION", role::SECTION.to_string()),
            ("SEARCH", role::SEARCH.to_string()),
            ("LIST_ITEM", role::LIST_ITEM.to_string()),
            ("PARAGRAPH", role::PARAGRAPH.to_string()),
        ],
    );

    out.push_str("\n// Components (spec/PRIMITIVES.md)\n");
    write_consts(&mut out, 
        "COMPONENT_",
        &[
            ("TEXT", fmt_u16(component_type::TEXT)),
            ("IMAGE", fmt_u16(component_type::IMAGE)),
            ("COLOR", fmt_u16(component_type::COLOR)),
            ("SHAPE", fmt_u16(component_type::SHAPE)),
            ("DIVIDER", fmt_u16(component_type::DIVIDER)),
            ("SPACER", fmt_u16(component_type::SPACER)),
            ("PROGRESS_VIEW", fmt_u16(component_type::PROGRESS_VIEW)),
            ("GAUGE", fmt_u16(component_type::GAUGE)),
            ("VSTACK", fmt_u16(component_type::VSTACK)),
            ("HSTACK", fmt_u16(component_type::HSTACK)),
            ("ZSTACK", fmt_u16(component_type::ZSTACK)),
            ("GRID", fmt_u16(component_type::GRID)),
            ("SCROLLVIEW", fmt_u16(component_type::SCROLLVIEW)),
            ("LAZY_VGRID", fmt_u16(component_type::LAZY_VGRID)),
            ("LAZY_HGRID", fmt_u16(component_type::LAZY_HGRID)),
            ("LAZY_VSTACK", fmt_u16(component_type::LAZY_VSTACK)),
            ("LAZY_HSTACK", fmt_u16(component_type::LAZY_HSTACK)),
            ("BUTTON", fmt_u16(component_type::BUTTON)),
            ("TEXT_FIELD", fmt_u16(component_type::TEXT_FIELD)),
            ("TEXT_EDITOR", fmt_u16(component_type::TEXT_EDITOR)),
            ("TOGGLE", fmt_u16(component_type::TOGGLE)),
            ("SLIDER", fmt_u16(component_type::SLIDER)),
            ("STEPPER", fmt_u16(component_type::STEPPER)),
            ("DATE_PICKER", fmt_u16(component_type::DATE_PICKER)),
            ("PICKER", fmt_u16(component_type::PICKER)),
            ("MENU", fmt_u16(component_type::MENU)),
            ("COLOR_PICKER", fmt_u16(component_type::COLOR_PICKER)),
            ("COMMENT", fmt_u16(component_type::COMMENT)),
        ],
    );
    out
}

/// Emit the token conventions (`lib/typescript/src/generated/tokens-core.ts`)
/// from `pathland_render_html::token_spec` — the pure data + pure functions the
/// DOM client imports, so the `--pl-*` naming / length rules cannot drift.
pub fn emit_tokens_core_ts() -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo run -p pathland-ts-codegen` (lib/rust). Do not edit.\n\
         // Canonical design-token conventions from `pathland-render-html::token_spec`\n\
         // (spec/TOKENS.md). Regenerate with `npm run regen`.\n\n",
    );
    let q = |s: &str| format!("{s:?}");
    let list = |items: &[&str]| {
        let joined: Vec<String> = items.iter().map(|s| q(*s)).collect();
        format!("[{}]", joined.join(", "))
    };
    let pair_list = |items: &[(&str, &str)]| {
        let joined: Vec<String> = items
            .iter()
            .map(|(a, b)| format!("[{}, {}]", q(*a), q(*b)))
            .collect();
        format!("[{}]", joined.join(", "))
    };
    writeln!(out, "export const DARK_PREFIX = {};", q(token_spec::DARK_PREFIX)).unwrap();
    writeln!(out, "export const VAR_PREFIX = {};", q(token_spec::VAR_PREFIX)).unwrap();
    writeln!(out, "export const SPACE_FAMILY = {};", q(token_spec::SPACE_FAMILY)).unwrap();
    writeln!(
        out,
        "export const LENGTH_PREFIXES: readonly string[] = {};",
        list(token_spec::LENGTH_PREFIXES)
    )
    .unwrap();
    writeln!(
        out,
        "export const LENGTH_PREFIX_SUFFIX: ReadonlyArray<readonly [string, string]> = {};",
        pair_list(token_spec::LENGTH_PREFIX_SUFFIX)
    )
    .unwrap();
    writeln!(
        out,
        "export const LENGTH_EXACT: readonly string[] = {};",
        list(token_spec::LENGTH_EXACT)
    )
    .unwrap();
    writeln!(
        out,
        "export const LENGTH_ELEVATION_SUFFIXES: readonly string[] = {};",
        list(token_spec::LENGTH_ELEVATION_SUFFIXES)
    )
    .unwrap();
    out.push_str(
        "\n/** The canonical CSS custom property for a token path: `--pl-` prefix, `.` → `-`.\n \
         *  The `dark.` scheme prefix is stripped — the dark variant overrides the same\n \
         *  variable inside a media query. */\n\
         export function tokenToCssVar(path: string): string {\n\
         \x20 const bare = path.startsWith(DARK_PREFIX) ? path.slice(DARK_PREFIX.length) : path;\n\
         \x20 return VAR_PREFIX + bare.replace(/[^A-Za-z0-9_-]/g, \"-\");\n\
         }\n\n\
         /** Whether a token path selects the dark variant. */\n\
         export function isDarkToken(path: string): boolean {\n\
         \x20 return path.startsWith(DARK_PREFIX);\n\
         }\n\n\
         /** Token paths whose F32 values are CSS lengths (emitted with `px`). */\n\
         export function isLengthToken(path: string): boolean {\n\
         \x20 for (const prefix of LENGTH_PREFIXES) {\n\
         \x20\x20 if (path.startsWith(prefix)) return true;\n\
         \x20 }\n\
         \x20 for (const [prefix, suffix] of LENGTH_PREFIX_SUFFIX) {\n\
         \x20\x20 if (path.startsWith(prefix) && path.endsWith(suffix)) return true;\n\
         \x20 }\n\
         \x20 if (LENGTH_EXACT.includes(path)) return true;\n\
         \x20 return path.startsWith(\"elevation.\") && LENGTH_ELEVATION_SUFFIXES.some((s) => path.endsWith(s));\n\
         }\n\n\
         /** Resolve a `DESIGN_TOKEN` property reference to a CSS expression: the\n\
          *  generative `space.<N>` family resolves to `calc(var(--pl-space-base) * N)`. */\n\
         export function resolveTokenCssRef(path: string): string {\n\
         \x20 const bare = path.startsWith(DARK_PREFIX) ? path.slice(DARK_PREFIX.length) : path;\n\
         \x20 if (bare.startsWith(SPACE_FAMILY)) {\n\
         \x20\x20 const rest = bare.slice(SPACE_FAMILY.length);\n\
         \x20\x20 if (rest.length > 0 && !Number.isNaN(Number(rest))) {\n\
         \x20\x20\x20 return `calc(var(--pl-space-base) * ${rest})`;\n\
         \x20\x20 }\n\
         \x20 }\n\
         \x20 return `var(${tokenToCssVar(bare)})`;\n\
         }\n",
    );
    out
}

/// Emit the role→semantic-element conventions (`generated/role-spec.ts`) from
/// `pathland_render_html::role_spec` — the single source the Rust SSR renderer
/// and the DOM client share for semantic tags / ARIA fallbacks.
pub fn emit_role_spec_ts() -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo run -p pathland-ts-codegen` (lib/rust). Do not edit.\n\
         // Canonical ROLE → semantic HTML element mapping from\n\
         // `pathland-render-html::role_spec` (spec/OPCODE.md §semantic properties).\n\
         // Regenerate with `npm run regen`.\n\n",
    );
    let q = |s: &str| format!("{s:?}");
    let nums = |items: &[u16]| {
        let joined: Vec<String> = items.iter().map(|v| format!("{v:#06x}")).collect();
        format!("[{}]", joined.join(", "))
    };
    let pair_list = |items: &[(u8, &str)]| {
        let joined: Vec<String> = items
            .iter()
            .map(|(r, s)| format!("[{r}, {}]", q(s)))
            .collect();
        format!("[{}]", joined.join(", "))
    };
    writeln!(
        out,
        "export const GENERIC_COMPONENTS: readonly number[] = {};",
        nums(role_spec::GENERIC_COMPONENTS)
    )
    .unwrap();
    writeln!(
        out,
        "export const NATIVE_ROLE_COMPONENTS: readonly number[] = {};",
        nums(role_spec::NATIVE_ROLE_COMPONENTS)
    )
    .unwrap();
    out.push_str(
        "export interface RoleTag {\n\
         \x20 role: number;\n\
         \x20 tag: string;\n\
         \x20 aria: string;\n\
         }\n\n",
    );
    out.push_str("export const ROLE_TAGS: readonly RoleTag[] = [\n");
    for rt in role_spec::ROLE_TAGS {
        writeln!(out, "  {{ role: {}, tag: {}, aria: {} }},", rt.role, q(rt.tag), q(rt.aria)).unwrap();
    }
    out.push_str("];\n\n");
    out.push_str("export const ROLE_ARIA: ReadonlyArray<readonly [number, string]> = ");
    out.push_str(&pair_list(role_spec::ROLE_ARIA));
    out.push_str(";\n\n");
    out.push_str(
        "/** A shell's role behavior (see `pathland-render-html::role_spec`).\n \
         *  Generic `div`/`span` shells may be retagged; native controls convey\n \
         *  their own role; anything else only gets an ARIA attribute. */\n\
         export type ShellKind = \"generic\" | \"native\" | \"other\";\n\n\
         /** The semantic tag a `(shell kind, role)` pair resolves to, or null. */\n\
         export function semanticTag(kind: ShellKind, role: number): string | null {\n\
         \x20 if (kind !== \"generic\") return null;\n\
         \x20 const found = ROLE_TAGS.find((r) => r.role === role);\n\
         \x20 return found ? found.tag : null;\n\
         }\n\n\
         /** The ARIA `role` value to emit for `(shell kind, role)`, or null when\n\
          *  the element already conveys the role (a semantic tag or a native control). */\n\
         export function ariaRole(kind: ShellKind, role: number): string | null {\n\
         \x20 if (kind === \"native\") return null;\n\
         \x20 const tagged = ROLE_TAGS.find((r) => r.role === role);\n\
         \x20 if (tagged) {\n\
         \x20\x20 return kind === \"generic\" ? null : tagged.aria;\n\
         \x20 }\n\
         \x20 const found = ROLE_ARIA.find(([r]) => r === role);\n\
         \x20 return found ? found[1] : null;\n\
         }\n",
    );
    out
}

fn main() -> io::Result<()> {
    let consts = constants_ts_path();
    std::fs::write(&consts, emit_constants_ts())?;
    println!("wrote {}", consts.display());
    let tokens = tokens_core_ts_path();
    if let Some(parent) = tokens.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&tokens, emit_tokens_core_ts())?;
    println!("wrote {}", tokens.display());
    let roles = role_spec_ts_path();
    if let Some(parent) = roles.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&roles, emit_role_spec_ts())?;
    println!("wrote {}", roles.display());
    Ok(())
}